title: 'Add <PROJECT NAME> to "Projects Using EditorConfig"'
body:  
  - type: textarea
    attributes:
      label: Request
      value: |
        Please add <PROJECT NAME> to "Projects Using EditorConfig"

        ```
        [<PROJECT NAME>](<PROJECT HOMEPAGE>) ([source](<LINK TO .editorconfig OF THE PROJECT)) -- <PROJECT DESCRIPTION>
        ```
